// ? Powered by Google Translate
import {
    Fragment as 파편,
    StrictMode as 엄격한모드,
    Profiler as 프로파일러,
    Suspense as 대기,
    Children as 자식,
    Component as 구성요소,
    PureComponent as 순수구성요소,
    // @ts-ignore
    __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED as __비밀_내부는_사용하지_마세요_그렇지_않으면_해고됩니다,
    cloneElement as 요소복제,
    createContext as 맥락생성,
    createElement as 요소생성,
    createFactory as 공장생성,
    createRef as 참조생성,
    forwardRef as 참조전달,
    isValidElement as 올바른요소인가,
    lazy as 게으른,
    memo as 메모,
    useCallback as 사용다시부르다,
    useContext as 사용요소,
    useDebugValue as 사용벌레잡이값,
    useEffect as 사용효과,
    useImperativeHandle as 사용필수적인처리,
    useLayoutEffect as 사용레이아웃효과,
    useRef as 사용참조,
    useState as 사용상태,
    version as 버전
} from 'react'

export {
    파편,
    엄격한모드,
    프로파일러,
    대기,
    자식,
    구성요소,
    순수구성요소,
    __비밀_내부는_사용하지_마세요_그렇지_않으면_해고됩니다,
    요소복제,
    맥락생성,
    요소생성,
    공장생성,
    참조생성,
    참조전달,
    올바른요소인가,
    게으른,
    메모,
    사용다시부르다,
    사용요소,
    사용벌레잡이값,
    사용효과,
    사용필수적인처리,
    사용레이아웃효과,
    사용참조,
    사용상태,
    버전
}

export const 반응형 = {
    파편,
    엄격한모드,
    프로파일러,
    대기,
    자식,
    구성요소,
    순수구성요소,
    __비밀_내부는_사용하지_마세요_그렇지_않으면_해고됩니다,
    요소복제,
    맥락생성,
    요소생성,
    공장생성,
    참조생성,
    참조전달,
    올바른요소인가,
    게으른,
    메모,
    사용다시부르다,
    사용요소,
    사용벌레잡이값,
    사용효과,
    사용필수적인처리,
    사용레이아웃효과,
    사용참조,
    사용상태,
    버전
}
export default 반응형;
